#!/bin/zsh
aws s3api create-bucket --acl public-read --bucket honeycomb.cruftbusters.com
aws s3api put-bucket-policy --bucket honeycomb.cruftbusters.com --policy file://scripts/bucket-policy.json
output=`aws cloudfront create-distribution --distribution-config file://scripts/distribution-config.json`
domainName=`echo $output | jq .Distribution.DomainName -r`
changeBatch=`jq ".Changes[].ResourceRecordSet.ResourceRecords[].Value=\"$domainName\"" scripts/change-batch.json`
aws route53 change-resource-record-sets --hosted-zone-id /hostedzone/Z2RH2FZB1VIOO8 --change-batch file://<(echo $changeBatch)
